import type { Metadata } from "next";
import "./globals.css";
import { bryndan,geist, doublebass } from "@/constants/fonts";
import { Providers } from "@/components/providers";

export const metadata: Metadata = {
  title: "The English Crab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geist.variable}  ${doublebass.variable} ${bryndan.variable}  font-geist`}>
          <Providers>
            {children}
          </Providers>
      </body>
    </html>
  );
}
