// src/app/layout.tsx (o RootLayout.tsx)

import type { Metadata } from "next";
import "./globals.css";
// Importamos nuestras fuentes definidas en constants/fonts:
import { bryndan,geist, doublebass } from "@/constants/fonts";
import { Providers } from "@/components/providers";
import { ScrollContainer } from "react-nice-scroll";

export const metadata: Metadata = {
  title: "The English Crab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geist.variable}  ${doublebass.variable} ${bryndan.variable}  font-geist`}>
        <Providers>
          
    <ScrollContainer>
      
          {children}
          
    </ScrollContainer>
          </Providers>
      </body>
    </html>
  );
}
